language: python
os: linux
dist: xenial
python:
- 3.7
- &mainstream_python 3.8
- 3.9
- nightly
install:
- "pip install tox-travis"
- "pip install coveralls"
script:
- "tox"
after_success:
- coveralls
- "tox -e benchmarks
